/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MaterialBeautifyChineseStudy {
        /**
          * Recognized card orientations: `question` | `answer`
         */
        "cardOrientation": string;
        /**
          * Recognized card types: `recognition` | `sentence` | `tones` | `writing` | `meaning` | `audio` | `secondary-sentence` | `secondary-recognition`
         */
        "cardType": string;
        /**
          * Option to always generate secondary character values and phonic values
         */
        "forceAutoGeneration": boolean;
        /**
          * All English language words allowed
         */
        "meaning": string;
        /**
          * Most forms of numbered pinyin allowed
         */
        "numberedPinyin": string;
        /**
          * Recognized phonics: `pinyin` | `zhuyin`
         */
        "preferredPhonic": string;
        /**
          * All characters allowed
         */
        "primaryCharacter": string;
        /**
          * All characters allowed
         */
        "primaryCharacterSentence": string;
        /**
          * Recognized hanzi typoes: 'simplified' | 'traditional'
         */
        "primaryHanziType": string;
        /**
          * All characters allowed
         */
        "secondaryCharacter": string;
        /**
          * All characters allowed
         */
        "secondaryCharacterSentence": string;
        /**
          * All English language words allowed
         */
        "sentenceMeaning": string;
        /**
          * Most forms of numbered pinyin allowed
         */
        "sentenceNumberedPinyin": string;
    }
}
declare global {
    interface HTMLMaterialBeautifyChineseStudyElement extends Components.MaterialBeautifyChineseStudy, HTMLStencilElement {
    }
    var HTMLMaterialBeautifyChineseStudyElement: {
        prototype: HTMLMaterialBeautifyChineseStudyElement;
        new (): HTMLMaterialBeautifyChineseStudyElement;
    };
    interface HTMLElementTagNameMap {
        "material-beautify-chinese-study": HTMLMaterialBeautifyChineseStudyElement;
    }
}
declare namespace LocalJSX {
    interface MaterialBeautifyChineseStudy {
        /**
          * Recognized card orientations: `question` | `answer`
         */
        "cardOrientation"?: string;
        /**
          * Recognized card types: `recognition` | `sentence` | `tones` | `writing` | `meaning` | `audio` | `secondary-sentence` | `secondary-recognition`
         */
        "cardType"?: string;
        /**
          * Option to always generate secondary character values and phonic values
         */
        "forceAutoGeneration"?: boolean;
        /**
          * All English language words allowed
         */
        "meaning"?: string;
        /**
          * Most forms of numbered pinyin allowed
         */
        "numberedPinyin"?: string;
        /**
          * Recognized phonics: `pinyin` | `zhuyin`
         */
        "preferredPhonic"?: string;
        /**
          * All characters allowed
         */
        "primaryCharacter"?: string;
        /**
          * All characters allowed
         */
        "primaryCharacterSentence"?: string;
        /**
          * Recognized hanzi typoes: 'simplified' | 'traditional'
         */
        "primaryHanziType"?: string;
        /**
          * All characters allowed
         */
        "secondaryCharacter"?: string;
        /**
          * All characters allowed
         */
        "secondaryCharacterSentence"?: string;
        /**
          * All English language words allowed
         */
        "sentenceMeaning"?: string;
        /**
          * Most forms of numbered pinyin allowed
         */
        "sentenceNumberedPinyin"?: string;
    }
    interface IntrinsicElements {
        "material-beautify-chinese-study": MaterialBeautifyChineseStudy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "material-beautify-chinese-study": LocalJSX.MaterialBeautifyChineseStudy & JSXBase.HTMLAttributes<HTMLMaterialBeautifyChineseStudyElement>;
        }
    }
}
