name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config user.email "github-actions@github.com"
      - run: git config user.name "github-actions"
      # this action executes on a release which already creates a tag
      #- run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      # make a manual addition to the package.json file then build a release on github
      # if we rely on this script to do it for us the release will be created BEFORE the new
      # version is defined
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
